print('===== DESAFIO 04 =====')
n = input('Digite algo: ')
print(f'Qual é o tipo de {n}? ')
print(type(n))
print(f'{n} é um número? ')
print(n.isalnum())
print(f'{n} é uma string? ')
print(n.isalpha())
print(f'{n} está em CAIXA ALTA? ')
print(n.isupper())
